[package]
name = "decka"
version = "0.1.0"
edition = "2021"
description = "Decka Cards"
authors = [ "Timothy Jay" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.9.0"